# Generated by Django 4.2.3 on 2023-07-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='books_picture',
            field=models.ImageField(default='default_book.png', upload_to=''),
        ),
    ]
