# Generated by Django 4.2.3 on 2023-07-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_time',
        ),
    ]
