# Generated by Django 4.2.3 on 2023-08-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='craeted_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
