# Generated by Django 4.2.3 on 2023-08-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_craeted_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
