# Generated by Django 4.2.3 on 2023-08-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_reviewlike_reviewlike_postlikeunique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewLike',
        ),
    ]
