# Generated by Django 4.2.3 on 2023-08-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_reviewlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewLike',
        ),
    ]
