# Generated by Django 4.2.3 on 2023-08-27 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0012_delete_reviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.ManyToManyField(related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
